_target_: lerobot.common.robot_devices.robots.manipulator.ManipulatorRobot
robot_type: so100_bimanual
calibration_dir: .cache/calibration/so100_bimanual

# `max_relative_target` limits the magnitude of the relative positional target vector for safety purposes.
# Set this to a positive scalar to have the same value for all motors, or a list that is the same length as
# the number of motors in your follower arms.
max_relative_target: null

leader_arms:
  left:
    _target_: lerobot.common.robot_devices.motors.feetech.FeetechMotorsBus
    port: left_leader
    motors:
      # name: (index, model)
      shoulder_pan: [1, "sts3215"]
      shoulder_lift: [2, "sts3215"]
      elbow_flex: [3, "sts3215"]
      wrist_flex: [4, "sts3215"]
      wrist_roll: [5, "sts3215"]
      gripper: [6, "sts3215"]
  right:
    _target_: lerobot.common.robot_devices.motors.feetech.FeetechMotorsBus
    port: right_leader
    motors:
      # name: (index, model)
      shoulder_pan: [1, "sts3215"]
      shoulder_lift: [2, "sts3215"]
      elbow_flex: [3, "sts3215"]
      wrist_flex: [4, "sts3215"]
      wrist_roll: [5, "sts3215"]
      gripper: [6, "sts3215"]

follower_arms:
  left:
    _target_: lerobot.common.robot_devices.motors.feetech.FeetechMotorsBus
    port: left_follower
    motors:
      # name: (index, model)
      shoulder_pan: [1, "sts3215"]
      shoulder_lift: [2, "sts3215"]
      elbow_flex: [3, "sts3215"]
      wrist_flex: [4, "sts3215"]
      wrist_roll: [5, "sts3215"]
      gripper: [6, "sts3215"]
  right:
    _target_: lerobot.common.robot_devices.motors.feetech.FeetechMotorsBus
    port: right_follower
    motors:
      # name: (index, model)
      shoulder_pan: [1, "sts3215"]
      shoulder_lift: [2, "sts3215"]
      elbow_flex: [3, "sts3215"]
      wrist_flex: [4, "sts3215"]
      wrist_roll: [5, "sts3215"]
      gripper: [6, "sts3215"]

cameras:
  high:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: high
    fps: 30
    width: 640
    height: 480
  low:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: low
    fps: 30
    width: 640
    height: 480
  left_wrist:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: left_wrist
    fps: 30
    width: 640
    height: 480
  right_wrist:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: right_wrist
    fps: 30
    width: 640
    height: 480
