
dataset:
  repo_id: hhws/so100_bimanual_transfer_6
  root: D:/projects/lerobot_datasets
  image_transforms:
    enable: false
policy:
  type: act
  vision_backbone: resnet18
  pretrained_backbone_weights: ResNet18_Weights.IMAGENET1K_V1
  chunk_size: 100
  kl_weight: 100.0
  optimizer_lr: 1e-5
  optimizer_lr_backbone: 1e-5
  optimizer_weight_decay: 1e-4
  use_amp: true
  concat_all_camera_imgs: true

output_dir: D:/projects/lerobot_trained_models/act_so100_bimanual_transfer_9
job_name: act_so100_bimanual_transfer_9
batch_size: 8
steps: 150000
save_freq: 10000
num_workers: 1

