dataset:
  repo_id: hhws/piper_2
  root: D:/projects/lerobot_datasets
  image_transforms:
    enable: false
  # episodes: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]

policy:
  type: diffusion
  spatial_softmax_num_keypoints: 16
  use_separate_rgb_encoder_per_camera: false

output_dir: D:/projects/lerobot_trained_models/piper_4_diffusion
job_name: piper_4_diffusion
batch_size: 8
steps: 200000
save_freq: 10000
num_workers: 2

