
dataset:
  repo_id: hhws/so100_bimanual_cube_1
  root: D:/projects/lerobot_datasets
  image_transforms:
    enable: false

output_dir: outputs/train/pi0_so100_bimanual_cube_1
job_name: pi0_so100_bimanual_cube_1
batch_size: 8
steps: 10000
save_freq: 1000