robot:
  type: so100_bimanual
  # type: so100_left
  # type: so100_right
  cameras: {}
control:
  type: calibrate
  # arms: ["left_follower", "left_leader"]
  # arms: ["right_follower", "right_leader"]
  # arms: ["right_leader"]
  # arms: ["right_follower"]
  # arms: ["left_follower"]
  arms: ["left_leader", "right_leader"]