robot:
  type: sam01_follower_end_effector
  port: left_follower
  id: robot_arm_follower_left
  urdf_path: C:\Users\chlai\projects\lerobot\assets\sam_arm_left

teleop:
  type: sam01_leader
  port: left_leader
  id: robot_arm_leader_left

