robot:
  type: so100_follower
  id: left_follower
  port: left_follower
  cameras:
    high:
      type: opencv
      index_or_path: high
      width: 640
      height: 480
      fps: 30
    wrist:
      type: opencv
      index_or_path: left_wrist
      width: 640
      height: 480
      fps: 30
teleop:
  type: so100_leader
  id: left_leader
  port: left_leader

display_data: true
