# robot:
#   # type: piper_left
#   type: so100_bimanual

# control:
#   type: test_policy
#   policy_name: act
#   n_action_steps: 100
#   task:
#   fps: 30
#   inference_time_s: 300
#   device: cuda
#   # pretrained_name_or_path: D:/projects/lerobot_trained_models/act_so100_bimanual_clothes_6/checkpoints/last/pretrained_model
#   pretrained_name_or_path: C:/Users/chlai/projects/lerobot_trained_models/act_so100_bimanual_cloth_2/checkpoints/last/pretrained_model


robot:
  type: bi_sam01_follower
  id: robot_arm_follower
  left_arm_port: left_follower
  right_arm_port: right_follower
  cameras:
    high:
      type: opencv
      index_or_path: high
      width: 640
      height: 480
      fps: 30
#    low:
#      type: opencv
#      index_or_path: low
#      width: 640
#      height: 480
#      fps: 30
    left_wrist:
      type: opencv
      index_or_path: left_wrist
      width: 640
      height: 480
      fps: 30
    right_wrist:
      type: opencv
      index_or_path: right_wrist
      width: 640
      height: 480
      fps: 30
policy:
  type: act
  n_action_steps: 100
  device: cuda

task:
inference_time_s: 300
fps: 30
pretrained_name_or_path: C:/Users/chlai/projects/lerobot_trained_models/act_sam01_luosi_fenjian_load/checkpoints/last/pretrained_model
