robot:
  # type: piper_left
  type: so100_bimanual

control:
  type: test_policy
  policy_name: act
  n_action_steps: 100
  task:
  fps: 30
  inference_time_s: 300
  device: cuda
  # pretrained_name_or_path: D:/projects/lerobot_trained_models/act_so100_bimanual_clothes_6/checkpoints/last/pretrained_model
  pretrained_name_or_path: C:/Users/chlai/projects/lerobot_trained_models/act_so100_bimanual_cloth_2/checkpoints/last/pretrained_model

