dataset:
  repo_id: hhws/cai_duo_double
  root: C:/Users/chlai/projects/lerobot_datasets
  image_transforms:
    enable: false
  # episodes: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]

policy:
  type: act
  vision_backbone: resnet18
  pretrained_backbone_weights: ResNet18_Weights.IMAGENET1K_V1
  chunk_size: 100
  kl_weight: 50.0
  optimizer_lr: 1e-5
  optimizer_lr_backbone: 1e-5
  optimizer_weight_decay: 1e-4
  use_amp: true
  push_to_hub: false

output_dir: C:/Users/chlai/projects/lerobot_trained_models/act_sam01_cai_duo_double
job_name: act_sam01
batch_size: 8
steps: 100000
save_freq: 10000
num_workers: 6
resume: false

